Add regex matching for pastebin urls to send the raw version
Dorukyum/Pycord-Manager pull request #27
Opened 2022-03-12 20:12 UTC by jab416171

2022-03-13 07:29 UTC, Dorukyum commented
Hello, I think it would be better if we did the following:
1. Check if the guild is Pycord (`if message.guild == self.bot.pycord`)
2. List the links and send in one message (to prevent the bot from spamming)

2022-03-14 22:53 UTC, PythonIntermediateCoder approved these changes

2022-03-14 22:53 UTC, PythonIntermediateCoder commented on cogs/pycord.py
> +
You should remove the extra empty line, but the code looks pretty good.

2022-03-26 19:54 UTC, IlluminatiFish requested changes
Could maybe use a more specific regex to match pastebin urls to prevent FPs

Suggested regex:
`(https?://pastebin.com)/([a-zA-Z0-9]{8})`

Also you could tuple unpack the `match` variable as it will always be a pair of values (`base_url` & `paste_id`)

2022-04-01 16:58 UTC, Dorukyum commented on cogs/pycord.py
> +PASTEBIN_RE = re.compile(r"(http(?:s?)://pastebin.com)(?:/)(\w+?)(?!/\w+)\W")
Suggestion by @IlluminatiFish 
```suggestion
PASTEBIN_RE = re.compile(r"(https?://pastebin.com)/([a-zA-Z0-9]{8})")
```

2022-04-01 18:30 UTC, IlluminatiFish approved these changes
lgtm

2022-04-05 18:37 UTC, Dorukyum commented
I tested this and it works well but I'm thinking, why/how would this be useful?

2022-04-05 21:53 UTC, jab416171 commented
pastebin's default landing page has ads and is slow and obnoxious. the raw paste is just the text.
Chicc said ["we only accept pastebin links"](https://canary.discord.com/channels/881207955029110855/881309496385884180/952289683600183426) and it inspired me to add this feature.

2022-04-06 03:41 UTC, Dorukyum approved these changes
Looks good, thanks for your contribution

2022-04-06 03:41 UTC, merged